"use client";
import {FormEvent,useEffect,useState} from "react";

type User={id:string;displayName:string;username:string;role:"ADMIN"|"CAMERIERE"|"CASSIERE"};
type Table={id:string;table_number:number;status:string;waiter_name?:string;order_id?:number;account_name?:string;total?:number};
const api=async(method:string,body?:unknown,action?:string)=>{const r=await fetch(`/api/app${action?`?action=${action}`:""}`,{method,headers:{"content-type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d};
const money=(v:number|string=0)=>new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(+v);

export default function Home(){
  const [user,setUser]=useState<User|null|undefined>(undefined),[state,setState]=useState<any>(null),[view,setView]=useState("tavoli"),[error,setError]=useState("");
  const load=async()=>{const m=await api("GET",undefined,"me");setUser(m.user);if(m.user)setState(await api("GET",undefined,"state"))};
  useEffect(()=>{load().catch(()=>setUser(null))},[]);
  if(user===undefined)return <main className="center"><div className="loader"/></main>;
  if(!user)return <Access onDone={load}/>;
  const nav=user.role==="ADMIN"?["tavoli","ordini","utenti","impostazioni"]:user.role==="CASSIERE"?["tavoli","ordini"]:["tavoli"];
  return <main className="shell"><aside><div className="brand"><span>B</span><div><b>Baccanalia</b><small>Gestionale ristorazione</small></div></div><nav>{nav.map(n=><button className={view===n?"active":""} onClick={()=>setView(n)} key={n}>{n==="tavoli"?"▦":n==="ordini"?"▤":n==="utenti"?"♙":"⚙"} {n}</button>)}</nav><div className="profile"><b>{user.displayName}</b><small>{user.role}</small><button onClick={async()=>{await api("POST",{action:"logout"});setUser(null)}}>Esci</button></div></aside><section className="content"><header><div><p>19–23 AGOSTO 2026</p><h1>{view[0].toUpperCase()+view.slice(1)}</h1></div><span className="live">● Sistema collegato</span></header>{error&&<div className="alert">{error}</div>}{view==="tavoli"&&<Tables user={user} data={state} reload={load} fail={setError}/>} {view==="ordini"&&<Orders/>}{view==="utenti"&&<Users reload={load}/>} {view==="impostazioni"&&<Settings reload={load}/>}</section></main>
}

function Access({onDone}:{onDone:()=>void}){
  const [setup,setSetup]=useState(false),[form,setForm]=useState({displayName:"Francesco",username:"",password:""}),[error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();try{await api("POST",{action:setup?"setup":"login",...form});onDone()}catch(x){setError((x as Error).message)}}
  return <main className="access"><section><div className="logo">B</div><p className="overline">GESTIONALE SAGRA</p><h1>{setup?"Crea il primo amministratore":"Bentornato"}</h1><p>{setup?"Operazione disponibile solo quando il database non contiene utenti.":"Accedi con le credenziali create dall’amministratore."}</p><form onSubmit={submit}>{setup&&<label>Nome visualizzato<input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label>}<label>Nome utente<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}<button type="submit">{setup?"Crea admin":"Accedi"}</button></form><button className="link" onClick={()=>{setSetup(!setup);setError("")}}>{setup?"Torna al login":"Prima configurazione"}</button></section></main>
}

function Tables({user,data,reload,fail}:{user:User;data:any;reload:()=>void;fail:(x:string)=>void}){
  const [chosen,setChosen]=useState<Table|null>(null),[name,setName]=useState("");
  const tables:Table[]=data?.tables||[];
  async function open(){try{await api("POST",{action:"openTable",tableId:chosen?.id,accountName:name});setChosen(null);setName("");reload()}catch(e){fail((e as Error).message)}}
  return <><div className="legend"><span>● Disponibile</span><span>● Occupato</span><b>{tables.filter(t=>t.status==="LIBERO").length}/{tables.length} liberi</b></div><div className="tables">{tables.map(t=><button key={t.id} className={t.status.toLowerCase()} onClick={()=>user.role==="CAMERIERE"&&t.status==="LIBERO"&&setChosen(t)}><small>TAVOLO</small><strong>{String(t.table_number).padStart(2,"0")}</strong>{t.status==="LIBERO"?<><b>Disponibile</b><span>Tocca per aprire</span></>:<><b>{t.account_name}</b><span>{t.waiter_name} · {money(t.total)}</span></>}</button>)}</div>{!tables.length&&<div className="empty">L’admin deve inserire i tavoli nel database.</div>}{chosen&&<div className="modal-bg"><div className="modal"><small>APERTURA CONTO</small><h2>Tavolo {chosen.table_number}</h2><label>Nome del conto<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Es. Famiglia Rossi"/></label><div><button className="secondary" onClick={()=>setChosen(null)}>Annulla</button><button disabled={!name.trim()} onClick={open}>Apri conto</button></div></div></div>}</>
}
function Orders(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{api("GET",undefined,"orders").then(d=>setRows(d.orders))},[]);return <div className="panel"><div className="panel-title"><div><h2>Ordini chiusi</h2><p>Il cassiere vede la serata attiva; l’admin vede tutto lo storico.</p></div><strong>{money(rows.reduce((s,o)=>s+(+o.total),0))}</strong></div>{rows.map(o=><div className="order-row" key={o.id}><span className="pill">CHIUSO</span><div><b>Tavolo {o.table_number} · {o.account_name}</b><small>{o.order_code} · {new Date(o.closed_at).toLocaleString("it-IT")}</small></div><span>{o.waiter_name}</span><strong>{money(o.total)}</strong></div>)}{!rows.length&&<div className="empty">Nessun ordine chiuso.</div>}</div>}
function Users({reload}:{reload:()=>void}){const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState({displayName:"",username:"",password:"",role:"CAMERIERE"}),[msg,setMsg]=useState("");const load=()=>api("GET",undefined,"users").then(d=>setRows(d.users));useEffect(()=>{load()},[]);async function create(e:FormEvent){e.preventDefault();try{await api("POST",{action:"createUser",...form});setMsg("Utente creato");setForm({displayName:"",username:"",password:"",role:"CAMERIERE"});load();reload()}catch(x){setMsg((x as Error).message)}}return <div className="split"><section className="panel"><h2>Personale</h2>{rows.map(u=><div className="user-row" key={u.id}><span>{u.display_name[0]}</span><div><b>{u.display_name}</b><small>@{u.username}</small></div><strong>{u.role}</strong></div>)}</section><form className="panel form" onSubmit={create}><h2>Nuovo utente</h2><label>Nome<input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Username univoco<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Ruolo<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>CAMERIERE</option><option>CASSIERE</option></select></label>{msg&&<p>{msg}</p>}<button>Crea account</button></form></div>}
function Settings({reload}:{reload:()=>void}){const [n,setN]=useState("");return <div className="panel form"><h2>Aggiungi tavolo</h2><p>I tavoli vengono creati esclusivamente dall’amministratore.</p><label>Numero tavolo<input type="number" min="1" value={n} onChange={e=>setN(e.target.value)}/></label><button onClick={async()=>{await api("POST",{action:"addTable",tableNumber:+n});setN("");reload()}}>Aggiungi</button><hr/><h2>Apri serata</h2><button onClick={async()=>{await api("POST",{action:"openEvening",workDate:"2026-08-19"});reload()}}>Attiva 19 agosto 2026</button></div>}
